%LET CSVFILE = /gpfsFS2/sasdata/nfs/SCL_MOC_Analytics/Category/Appt_Access/Data/Appointment_Data.csv;



proc import datafile="&CSVFILE"
out=APPT_DATA_IMPORT
dbms=csv
replace;
run;



DATA dates;
	PERIOD_BEG = INTNX('WEEK', '11nov2018'd, -1, 'B');
	PERIOD_END = INTNX('WEEK', TODAY(), -1, 'E');
	format PERIOD_BEG PERIOD_END MMDDYY10.;

	
	/*FORMAT DESIRED: '2020-12-31' */	
	CALL SYMPUT('BEG_DT',PERIOD_BEG);
	CALL SYMPUT('END_DT',PERIOD_END);
RUN;

PROC SQL;
CREATE TABLE AFTER_HOURS AS 
SELECT * FROM APPT_DATA_IMPORT 
WHERE APPOINTMENT_TIME > &BEGIN_TIME;
QUIT;

PROC SQL;
CREATE TABLE FIRST_SEVEN_DAYS AS SELECT * FROM AFTER_HOURS HAVING APPOINTMENT_DATE>MIN(APPOINTMENT_DATE) 
AND APPOINTMENT_DATE<=MIN(APPOINTMENT_DATE)+7 ORDER BY APPOINTMENT_DATE;
QUIT;

DATA dates;
	PERIOD_BEG = INTNX('WEEK', '11nov2018'd, -1, 'B');
	PERIOD_END = INTNX('WEEK', TODAY(), -1, 'E');
	format PERIOD_BEG PERIOD_END MMDDYY10.;

	/*FORMAT DESIRED: TIMESTAMP'2020-12-31 00:00:00' */
	CALL SYMPUT('BEG_DT',"TIMESTAMP'" || PUT(PERIOD_BEG, YYMMDD10.) || " 00:00:00'");
	CALL SYMPUT('END_DT',"TIMESTAMP'" || PUT(PERIOD_END, YYMMDD10.) || " 11:59:59'");
	
	/*FORMAT DESIRED: '2020-12-31' */	
	CALL SYMPUT('BEG_DT',"'"||PUT(PERIOD_BEG,YYMMDD10.)||"'");
	CALL SYMPUT('END_DT',"'"||PUT(PERIOD_END,YYMMDD10.)||"'");
RUN;
%PUT prnt_beg_dt: &BEG_DT;

PROC SQL;
CREATE TABLE WEEKLY_LABELED AS SELECT *, week(APPOINTMENT_DATE) AS WEEK FROM AFTER_HOURS;
QUIT;


PROC SQL;
CREATE TABLE WEEKLY_REPEATS AS SELECT COUNT(PATIENT_ID) FROM WEEKLY_LABELED GROUP BY ;
quit;