%LET CSVFILE = /gpfsFS2/sasdata/nfs/SCL_MOC_Analytics/Category/Appt_Access/Data/Appointment_Data.csv;



proc import datafile="&CSVFILE"
out=APPT_DATA_IMPORT
dbms=csv
replace;
run;



%LET BEGIN_TIME='17:30:00't;

PROC SQL;
CREATE TABLE AFTER_HOURS AS 
SELECT * FROM APPT_DATA_IMPORT 
WHERE APPOINTMENT_TIME > &BEGIN_TIME;
QUIT;
PROC SQL;
SELECT APPOINTMENT_TIME FROM AFTER_HOURS 
HAVING APPOINTMENT_TIME=MAX(APPOINTMENT_TIME);
QUIT;

%LET SIXTHIRTY= '18:30:00't;
%LET SEVENTHIRTY= '19:30:00't;
%LET EIGHTTHIRTY= '20:30:00't;
%LET NINETHIRTY= '21:30:00't;

PROC SQL;
CREATE TABLE AFTER_HRS_HOURLY AS 
SELECT *, CASE  
	WHEN APPOINTMENT_TIME>=&BEGIN_TIME AND APPOINTMENT_TIME<&SIXTHIRTY THEN 'BLOCK1'
	WHEN APPOINTMENT_TIME>=&BEGIN_TIME AND APPOINTMENT_TIME<&SEVENTHIRTY THEN 'BLOCK2'
	WHEN APPOINTMENT_TIME>=&BEGIN_TIME AND APPOINTMENT_TIME<&EIGHTTHIRTY THEN 'BLOCK3'
	ELSE 'BLOCK4'
END AS HOURLY_SPLIT
FROM AFTER_HOURS;
QUIT;
PROC SQL;
CREATE TABLE AFTER_HRS_HOURLY AS 
SELECT *, 
CASE  
	WHEN APPOINTMENT_TIME>=&BEGIN_TIME AND APPOINTMENT_TIME<&SIXTHIRTY THEN 1
	ELSE 0 END AS BLOCK1,
CASE
	WHEN APPOINTMENT_TIME>=&SIXTHIRTY AND APPOINTMENT_TIME<&SEVENTHIRTY THEN 1 
	ELSE 0 END AS BLOCK2,
CASE
	WHEN APPOINTMENT_TIME>=&SEVENTHIRTY AND APPOINTMENT_TIME<&EIGHTTHIRTY THEN 1
	ELSE 0 END AS BLOCK3,
CASE
	WHEN APPOINTMENT_TIME>=&EIGHTTHIRTY  THEN 1
	ELSE 0 END AS BLOCK4
FROM AFTER_HOURS;
QUIT;

PROC SQL;
CREATE TABLE HOURLY_COUNT AS SELECT APPOINTMENT_DATE, 
	SUM(BLOCK1) AS FIVETHIRTY_SIXTHIRTY, 
	SUM(BLOCK2) AS SIXTHIRTY_SEVENTHIRTY,
	SUM(BLOCK3) AS SEVENTHIRTY_EIGHTTHIRTY,
	SUM(BLOCK4) AS EIGHTTHIRTY_NINETHIRTY
FROM AFTER_HRS_HOURLY 
GROUP BY APPOINTMENT_DATE;
QUIT;



/*MAX METHOD SOLUTION*/
PROC SQL;
CREATE TABLE HOURLY_MAX AS SELECT 
MAX(FIVETHIRTY_SIXTHIRTY) AS MAX_FIVETHIRTY_SIXTHIRTY,
MAX(SIXTHIRTY_SEVENTHIRTY) AS MAX_SIXTHIRTY_SEVENTHIRTY, 
MAX(SEVENTHIRTY_EIGHTTHIRTY) AS MAX_SEVENTHIRTY_EIGHTTHIRTY, 
MAX(EIGHTTHIRTY_NINETHIRTY) AS MAX_EIGHTTHIRTY_NINETHIRTY
FROM HOURLY_COUNT;
QUIT;


PROC SQL;
CREATE TABLE MAX_METHOD_EMPLOYEES AS SELECT
CEIL(MAX_FIVETHIRTY_SIXTHIRTY/4), CEIL(MAX_SIXTHIRTY_SEVENTHIRTY/4),
CEIL(MAX_SEVENTHIRTY_EIGHTTHIRTY/4), CEIL(MAX_EIGHTTHIRTY_NINETHIRTY/4)
FROM HOURLY_MAX;
QUIT;


/*AVERAGE METHOD SOLUTION*/
PROC SQL;
CREATE TABLE HOURLY_AVG AS SELECT 
AVG(FIVETHIRTY_SIXTHIRTY) AS AVG_FIVETHIRTY_SIXTHIRTY,
AVG(SIXTHIRTY_SEVENTHIRTY) AS AVG_SIXTHIRTY_SEVENTHIRTY, 
AVG(SEVENTHIRTY_EIGHTTHIRTY) AS AVG_SEVENTHIRTY_EIGHTTHIRTY, 
AVG(EIGHTTHIRTY_NINETHIRTY) AS AVG_EIGHTTHIRTY_NINETHIRTY
FROM HOURLY_COUNT;
QUIT;


PROC SQL;
CREATE TABLE AVG_METHOD_EMPLOYEES AS SELECT
CEIL(AVG_FIVETHIRTY_SIXTHIRTY/4) as EMP_FIVETHIRTY_SIXTHIRTY, 
CEIL(AVG_SIXTHIRTY_SEVENTHIRTY/4) AS EMP_SIXTHIRTY_SEVENTHIRTY,
CEIL(AVG_SEVENTHIRTY_EIGHTTHIRTY/4) AS EMP_SEVENTHIRTY_EIGHTTHIRTY, 
CEIL(AVG_EIGHTTHIRTY_NINETHIRTY/4) AS EMP_EIGHTTHIRTY_NINETHIRTY
FROM HOURLY_AVG;
QUIT;